export const TaskConstants = {
    INDEX_REQUEST: 'TASK_INDEX_REQUEST',
    INDEX_FAILURE: 'TASK_INDEX_FAILURE',
    INDEX_SUCCESS: 'TASK_INDEX_SUCCESS',

    CREATE_REQUEST: 'TASK_CREATE_REQUEST',
    CREATED_FAILURE: 'TASK_CREATED_FAILURE',
    CREATED_SUCCESS: 'TASK_CREATED_SUCCESS',

    SHOW_REQUEST: 'TASK_SHOW_REQUEST',
    SHOW_FAILURE: 'TASK_SHOW_FAILURE',
    SHOW_SUCCESS: 'TASK_SHOW_SUCCESS',

    UPDATE_REQUEST: 'TASK_UPDATE_REQUEST',
    UPDATED_FAILURE: 'TASK_UPDATED_FAILURE',
    UPDATED_SUCCESS: 'TASK_UPDATED_SUCCESS',

    DELETE_REQUEST: 'TASK_DELETE_REQUEST',
    DELETED_FAILURE: 'TASK_DELETED_FAILURE',
    DELETED_SUCCESS: 'TASK_DELETED_SUCCESS',
};
